
User.destroy_all
Adoption.destroy_all
Pokemon.destroy_all

#List_of_pokemon
bulbasaur = Pokemon.create(species_name: "Bulbasaur", pokemon_type: "Grass",size: 0.7, weight: 6.9, skill: "Vine Whip")
ivysaur = Pokemon.create(species_name: "Ivysaur", pokemon_type: "Grass", size: 1.0, weight: 13.0, skill: "Razor Leaf")
venusaur = Pokemon.create(species_name: "Venusaur", pokemon_type: "Grass", size: 12.0, weight: 100.0, skill: "Solar Beam")
charmander = Pokemon.create(species_name: "Charmander", pokemon_type: "Fire", size: 0.6, weight: 8.5, skill: "Ember")
charmeleon = Pokemon.create(species_name: "Charmeleon", pokemon_type: "Fire", size: 1.1, weight: 19.0, skill: "Flamethrower")
charizard = Pokemon.create(species_name: "Charizard", pokemon_type: "Fire", size: 1.7, weight: 90.5, skill: "Fire Blast")
squirtle = Pokemon.create(species_name: "Squirtle", pokemon_type: "Water", size: 0.5, weight: 9.0, skill: "Bubble")
wartortle = Pokemon.create(species_name: "Wartortle", pokemon_type: "Water", size: 1.0, weight: 22.5, skill: "Water Gun")
blastoise = Pokemon.create(species_name: "Blastoise", pokemon_type: "Water", size: 1.6, weight: 85.5, skill: "Hydro Pump")
# caterpie = Pokemon.create(species_name: "Caterpie", pokemon_type: "Bug", size: 0.3, weight: 2.9, skill: "String Shot")
# metapod = Pokemon.create(species_name: "Metapod", pokemon_type: "Bug", size: 0.7, weight: 9.9, skill: "Harden")
butterfree = Pokemon.create(species_name: "Butterfree", pokemon_type: "Bug", size: 1.1, weight: 32.0, skill: "Confusion")
# weedle = Pokemon.create(species_name: "Weedle", pokemon_type: "Bug", size: 0.3, weight: 3.2, skill: "Poison Sting")
# kakuna = Pokemon.create(species_name: "Kakuna", pokemon_type: "Bug", size: 0.6, weight: 10.0, skill: "Harden")
beedrill = Pokemon.create(species_name: "Beedrill", pokemon_type: "Bug", size: 1.0, weight: 29.5, skill: "Twin Needle")
# pidgey = Pokemon.create(species_name: "Pidgey", pokemon_type: "Flying", size: 0.3, weight: 1.8, skill: "Gust")
# pidgeotto = Pokemon.create(species_name: "Pidgeotto", pokemon_type: "Flying", size: 1.1, weight: 30.0, skill: "Twister")
pidgeot = Pokemon.create(species_name: "Pidgeot", pokemon_type: "Flying", size: 1.5, weight: 39.5, skill: "Wing Attack")
# rattata = Pokemon.create(species_name: "Rattata", pokemon_type: "Normal", size: 0.3, weight: 3.5, skill: "Quick Attack")
# raticate = Pokemon.create(species_name: "Raticate", pokemon_type: "Normal", size: 0.7, weight: 18.5, skill: "Hyper Fang")
# spearow = Pokemon.create(species_name: "Spearow", pokemon_type: "Normal", size: 0.3, weight: 2.0, skill: "Peck")
fearow = Pokemon.create(species_name: "Fearow", pokemon_type: "Normal", size: 1.2, weight: 38, skill: "Drill Peck")
ekans = Pokemon.create(species_name: "Ekans", pokemon_type: "Poison", size: 2.0, weight: 6.9, skill: "Bite")
arbok = Pokemon.create(species_name: "Arbok", pokemon_type: "Poison", size: 3.5, weight: 65.0, skill: "Acid")
pikachu = Pokemon.create(species_name: "Pikachu", pokemon_type: "Electric", size: 0.4, weight: 6.0, skill: "Thunder Shock")
raichu = Pokemon.create(species_name: "Raichu", pokemon_type: "Electric", size: 0.8, weight: 30.0, skill: "Thunder")
# sandshrew = Pokemon.create(species_name: "Sandshrew", pokemon_type: "Ground", size: 0.6, weight: 12.0, skill: "Rollout")
# sandslash = Pokemon.create(species_name: "Sandslash", pokemon_type: "Ground", size: 1.0, weight: 29.5, skill: "Earthquake")
nidoranf = Pokemon.create(species_name: "Nidoran-F", pokemon_type: "Poison", size: 0.4, weight: 7.0, skill: "Fury Swipes")
nidorina = Pokemon.create(species_name: "Nidorina", pokemon_type: "Poison", size: 0.8, weight: 20.0, skill: "Horn Attack")
nidoqueen = Pokemon.create(species_name: "Nidoqueen", pokemon_type: "Poison", size: 1.3, weight: 60.0, skill: "Ice Beam")
nidoranm = Pokemon.create(species_name: "Nidoran-M", pokemon_type: "Poison", size: 0.5, weight: 9.0, skill: "Fury Swipes")
nidorino = Pokemon.create(species_name: "Nidorino", pokemon_type: "Poison", size: 0.9, weight: 19.5, skill: "Horn Attack")
nidoking = Pokemon.create(species_name: "Nidoking", pokemon_type: "Poison", size: 1.4, weight: 62.0, skill: "Earthquake")
clefairy = Pokemon.create(species_name: "Clefairy", pokemon_type: "Fairy",size: 0.6, weight: 7.5, skill: "Metronome")
clefable = Pokemon.create(species_name: "Clefable", pokemon_type: "Fairy", size: 1.3, weight: 40.0, skill: "Metronome")
vulpix = Pokemon.create(species_name: "Vulpix", pokemon_type: "Fire", size: 0.6, weight: 9.9, skill: "Ember")
ninetales = Pokemon.create(species_name: "Ninetales", pokemon_type: "Fire",size: 1.1, weight: 19.9, skill: "Flamethrower")
jigglypuff = Pokemon.create(species_name: "Jigglypuff", pokemon_type: "Fairy", size: 0.5, weight: 5.5, skill: "Sing")
wigglytuff = Pokemon.create(species_name: "Wigglytuff", pokemon_type: "Fairy", size: 1.0, weight: 12.0, skill: "Body Slam")
# zubat = Pokemon.create(species_name: "Zubat", pokemon_type: "Poison",size: 0.8, weight: 7.5, skill: "Supersonic")
golbat = Pokemon.create(species_name: "Golbat", pokemon_type: "Poison", size: 1.6, weight: 55.0, skill: "Confuse Ray")
oddish = Pokemon.create(species_name: "Oddish", pokemon_type: "Grass", size: 0.5, weight: 5.4, skill: "Absorb")
gloom = Pokemon.create(species_name: "Gloom", pokemon_type: "Grass",size: 0.8, weight: 8.6, skill: "Poison Powder")
vileplume = Pokemon.create(species_name: "Vileplume", pokemon_type: "Grass", size: 1.2, weight: 18.6, skill: "Giga Drain")
# paras = Pokemon.create(species_name: "Paras", pokemon_type: "Bug", size: 0.3, weight: 5.4, skill: "Spore")
# parasect = Pokemon.create(species_name: "Parasect", pokemon_type: "Bug",size: 1.0, weight: 29.5, skill: "Giga Drain")
venonat = Pokemon.create(species_name: "Venonat", pokemon_type: "Bug",size: 1.0, weight: 30.0, skill: "Foresight")
venomoth = Pokemon.create(species_name: "Venomoth", pokemon_type: "Bug", size: 1.5, weight: 12.5, skill: "Psybeam")
diglett = Pokemon.create(species_name: "Diglett", pokemon_type: "Ground", size: 0.2, weight: 0.8, skill: "Dig")
dugtrio = Pokemon.create(species_name: "Dugtrio", pokemon_type: "Ground",size: 0.7, weight: 33.3, skill: "Earthquake")
meowth = Pokemon.create(species_name: "Meowth", pokemon_type: "Normal",size: 0.4, weight: 4.2, skill: "Pay Day")
persian = Pokemon.create(species_name: "Persian", pokemon_type: "Normal", size: 1.0, weight: 32.0, skill: "Bite")
psyduck = Pokemon.create(species_name: "Psyduck", pokemon_type: "Water", size: 0.8, weight: 19.6, skill: "Confusion")
golduck = Pokemon.create(species_name: "Golduck", pokemon_type: "Water",size: 1.7, weight: 76.6, skill: "Hydro Pump")
mankey = Pokemon.create(species_name: "Mankey", pokemon_type: "Fighting", size: 0.5, weight: 28.0, skill: "Low Kick")
primeape = Pokemon.create(species_name: "Primeape", pokemon_type: "Fighting", size: 1.0, weight: 32.0, skill: "Seismic Toss")
growlith = Pokemon.create(species_name: "Growlith", pokemon_type: "Fire", size: 0.7, weight: 19.0, skill: "Flame Wheel")
arcanine = Pokemon.create(species_name: "Arcanine", pokemon_type: "Fire", size: 1.9, weight: 155.0, skill: "Flamethrower")
poliwag = Pokemon.create(species_name: "Poliwag", pokemon_type: "Water", size: 0.6, weight: 12.4, skill: "Hypnosis")
poliwhirl = Pokemon.create(species_name: "Poliwhirl", pokemon_type: "Water", size: 1.0, weight: 20.0, skill: "Water Gun")
poliwrath = Pokemon.create(species_name: "Poliwrath", pokemon_type: "Water", size: 1.3, weight: 54.0, skill: "Hydro Pump")
abra = Pokemon.create(species_name: "Abra", pokemon_type: "Psychic", size: 0.9, weight: 19.5, skill: "Teleport")
kadabra = Pokemon.create(species_name: "Kadabra", pokemon_type: "Psychic", size: 1.3, weight: 56.5, skill: "Confusion")
alakazam = Pokemon.create(species_name: "Alakazam", pokemon_type: "Psychic", size: 1.5, weight: 48.0, skill: "Psychic")
machop = Pokemon.create(species_name: "Machop", pokemon_type: "Fighting",size: 0.8, weight: 19.5, skill: "Karate Chop")
machoke = Pokemon.create(species_name: "Machoke", pokemon_type: "Fighting", size: 1.5, weight: 70.5, skill: "Seismic Toss")
machamp = Pokemon.create(species_name: "Machamp", pokemon_type: "Fighting", size: 1.6, weight: 130.0, skill: "Dynamic Punch")
bellsprout = Pokemon.create(species_name: "Bellsprout", pokemon_type: "Grass",size: 0.7, weight: 4.0, skill: "Vine Whip")
weepinbell = Pokemon.create(species_name: "Weepinbell", pokemon_type: "Grass", size: 1.0, weight: 6.4, skill: "Razer Leaf")
victreebel = Pokemon.create(species_name: "Victreebel", pokemon_type: "Grass", size: 1.7, weight: 15.5, skill: "Acid")
graveler = Pokemon.create(species_name: "Graveler", pokemon_type: "Rock",size: 1.0, weight: 105.0, skill: "Pay Day")
golem = Pokemon.create(species_name: "Golem", pokemon_type: "Rock", size: 1.4, weight: 300.0, skill: "Bite")
ponyta = Pokemon.create(species_name: "Ponyta", pokemon_type: "Fire", size: 1.0, weight: 30.0, skill: "Confusion")
rapidash = Pokemon.create(species_name: "Rapidash", pokemon_type: "Fire",size: 1.7, weight: 95.0, skill: "Flamethrower")
slowpoke = Pokemon.create(species_name: "Slowpoke", pokemon_type: "Water", size: 1.2, weight: 36.0, skill: "Confusion")
slowbro = Pokemon.create(species_name: "Slowbro", pokemon_type: "Water", size: 1.6, weight: 78.5, skill: "Psychic")
gengar = Pokemon.create(species_name: "Gengar", pokemon_type: "Ghost",size: 1.5, weight: 40.5, skill: "Shadow Ball")
onyx = Pokemon.create(species_name: "Onyx", pokemon_type: "Rock", size: 8.8, weight: 210.0, skill: "Rock throw")
hypno = Pokemon.create(species_name: "Hypno", pokemon_type: "Psychic", size: 1.6, weight: 75.6, skill: "Psychic")
exeggutor = Pokemon.create(species_name: "Exeggutor", pokemon_type: "Grass",size: 2.0, weight: 120.0, skill: "Giga Drain")
cubone = Pokemon.create(species_name: "Cubone", pokemon_type: "Ground", size: 0.4, weight: 6.5, skill: "Bone Club")
marowak = Pokemon.create(species_name: "Marowak", pokemon_type: "Ground", size: 1.0, weight: 45.0, skill: "Boomerang")
hitmonlee = Pokemon.create(species_name: "Hitmonlee", pokemon_type: "Fighting",size: 1.5, weight: 49.8, skill: "Mega Kick")
hitmonchan = Pokemon.create(species_name: "Hitmonchan", pokemon_type: "Fighting", size: 1.4, weight: 50.2, skill: "Mega Punch")
chansey = Pokemon.create(species_name: "Chansey", pokemon_type: "Normal", size: 1.1, weight: 34.6, skill: "Soft Boiled Egg")
horsea = Pokemon.create(species_name: "Horsea", pokemon_type: "Water", size: 0.4, weight: 8.0, skill: "Bubble")
seadra = Pokemon.create(species_name: "Seadra", pokemon_type: "Water", size: 1.2, weight: 25.0, skill: "Water Gun")
staryu = Pokemon.create(species_name: "Staryu", pokemon_type: "Water", size: 0.8, weight: 34.5, skill: "Water Gun")
starmie = Pokemon.create(species_name: "Starmie", pokemon_type: "Water", size: 1.1, weight: 80.0, skill: "Hydro Pump")
mr_mime = Pokemon.create(species_name: "Mr.Mime", pokemon_type: "Psychic", size: 1.3, weight: 54.5, skill: "Mimic")
scyther = Pokemon.create(species_name: "Scyther", pokemon_type: "Psychic", size: 1.5, weight: 56.0, skill: "Fury Cutter")
jynx = Pokemon.create(species_name: "Jynx", pokemon_type: "Ice", size: 1.4, weight: 40.6, skill: "Powder Snow")
electabuzz = Pokemon.create(species_name: "Electabuzz", pokemon_type: "Electric", size: 1.1, weight: 30.0, skill: "Thunder Punch")
gyarados = Pokemon.create(species_name: "Gyarados", pokemon_type: "Water", size: 6.5, weight: 235.0, skill: "Dragon Rage")
lapras = Pokemon.create(species_name: "Lapras", pokemon_type: "Ice", size: 2.5, weight: 220.0, skill: "Ice Beam")
eevee = Pokemon.create(species_name: "Eevee", pokemon_type: "Normal", size: 0.3, weight: 6.5, skill: "Bite")
vaporeon = Pokemon.create(species_name: "Vaporeon", pokemon_type: "Psychic", size: 1.0, weight: 29.0, skill: "Ice Beam")
jolteon = Pokemon.create(species_name: "Jolteon", pokemon_type: "Electric", size: 0.8, weight: 24.5, skill: "Thunder Bolt")
flareon = Pokemon.create(species_name: "Flareon", pokemon_type: "Fire", size: 0.9, weight: 25.0, skill: "Flamethrower")
porygon = Pokemon.create(species_name: "Porygon", pokemon_type: "Psychic", size: 0.8, weight: 36.5, skill: "Psychic")
omastar = Pokemon.create(species_name: "Omastar", pokemon_type: "Rock", size: 1.0, weight: 35.0, skill: "Ancient Power")
aerodactyl = Pokemon.create(species_name: "Aerodactyl", pokemon_type: "Rock", size: 1.8, weight: 59.0, skill: "Ancient Power")
snorlax = Pokemon.create(species_name: "Snorlax", pokemon_type: "Normal", size: 2.1, weight: 460.0, skill: "Rest")
articuno = Pokemon.create(species_name: "Articuno", pokemon_type: "Ice", size: 1.7, weight: 55.4, skill: "Blizzard")
zapdos = Pokemon.create(species_name: "Zapdos", pokemon_type: "Electric", size: 1.6, weight: 52.6, skill: "Thunder")
moltres = Pokemon.create(species_name: "Moltres", pokemon_type: "Fire", size: 2.0, weight: 60.0, skill: "Fire Blast")
dratini = Pokemon.create(species_name: "Dratini", pokemon_type: "Dragon", size: 1.8, weight: 3.3, skill: "Dragon Rage")
dragonair = Pokemon.create(species_name: "Dragonair", pokemon_type: "Dragon", size: 4.0, weight: 16.5, skill: "Slam")
dragonite = Pokemon.create(species_name: "Dragonite", pokemon_type: "Dragon", size: 2.2, weight: 210, skill: "Dragon Breath")
mewtwo = Pokemon.create(species_name: "Mewtwo", pokemon_type: "Psychic", size: 2.0, weight: 122.0, skill: "Psychic")
mew = Pokemon.create(species_name: "Mew", pokemon_type: "Psychic", size: 0.4, weight: 4.0, skill: "Psychic")





#add user instance assigned pokemon
chris = User.create(username: "chris123", password: "abc")
chris.save
carlos = User.create(username: "carlos123", password: "abc")
carlos.save
puts "seeded"


#change password
